ResourceException: avoid NotSerializableException (#1403)
* ResourceException: avoid NotSerializableException

- non-serializable internal attributes (status, request, and message) marked as transient
- this is to allow ResourceException to be serialized, passing over the message and stack-trace (which is typically all that is needed to show the error or print it in the log)
- fixes issue #1402

* Add disclaimer about default serialization

Disclaimer needed now that default serialization silently works.

---------

Co-authored-by: Tim Peierls <237258+Tembrel@users.noreply.github.com>